// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full border-b-[0.05rem] h-16 flex items-center justify-between\"><div class=\"h-full flex items-center border-r-[0.05rem] \"><a class=\"mx-2 text-white font-bold text-4xl font-silkscreen \" href=\"/\">madHOSS</a></div><details class=\"h-full items-stretch flex sm:hidden dropdown w-16\" id=\"navbutton\"><summary class=\"h-full btn btn-outline btn-primary border-y-0 border-r-0\"><svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" class=\"inline-block w-5 h-5 stroke-current\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></summary><div class=\"dropdown-content w-screen h-screen bg-base-100 !fixed left-0 z-[999]\"><div class=\"h-full flex flex-col items-center justify-start\"><a class=\"w-full btn btn-outline border-x-0 \" href=\"/feed\"><div class=\"text-neutral font-bold text-lg text-primary\">Feed</div></a> <a class=\"w-full btn btn-outline border-x-0\" href=\"/projects\"><div class=\"text-neutral font-bold text-lg text-primary\">Projects</div></a> <a class=\"w-full btn btn-outline border-x-0\" href=\"/me\"><div class=\"text-neutral font-bold text-lg text-primary\">Me</div></a><div class=\"h-full\"><div class=\"h-full bg-base-300\"></div></div></div></div></details><div class=\"h-full items-stretch hidden sm:flex\"><a class=\"h-full btn btn-outline border-y-0 border-r-0 \" href=\"/feed\"><div class=\"text-neutral font-bold text-primary\">Feed</div></a> <a class=\"h-full btn btn-outline border-y-0 border-r-0 \" href=\"/projects\"><div class=\"text-neutral font-bold text-primary\">Projects</div></a> <a class=\"h-full btn btn-outline border-y-0 border-r-0 \" href=\"/me\"><div class=\"text-neutral font-bold text-primary\">Me</div></a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
